#!/usr/bin/env ruby
require 'securerandom'
require 'base64'

message = ARGV[0]
key = SecureRandom.random_bytes(message.length)
ciphertext = ""

# XOR each byte of the message with the corresponding
# byte of the key
message.each_byte.with_index do |b, i|
  ciphertext << (b^key[i].ord).chr
end

puts "Key:        #{Base64.strict_encode64 key}"
puts "Ciphertext: #{Base64.strict_encode64 ciphertext}"
