#!/usr/bin/env ruby
require 'securerandom'
require 'base64'

ciphertext = Base64.strict_decode64(ARGV[0])
key = Base64.strict_decode64(ARGV[1])
message = ""

# XOR each byte of the ciphertext with the corresponding
# byte of the key
ciphertext.each_byte.with_index do |b, i|
  message << (b^key[i].ord).chr
end

puts "Plaintext: #{message}"
